# Generated by Django 2.2.10 on 2021-05-30 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='discription',
            new_name='description',
        ),
    ]
