# Generated by Django 2.2.10 on 2021-05-31 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20210530_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'вопрос', 'verbose_name_plural': 'вопросы'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'опрос', 'verbose_name_plural': 'опросы'},
        ),
        migrations.AlterModelOptions(
            name='surveysession',
            options={'verbose_name': 'сессия опроса', 'verbose_name_plural': 'сессии опросов'},
        ),
    ]
