version: '3.7'

services:
  app:
    build: ./fab_resh
    volumes:
      - ./fab_resh:/fab_resh
    command:
      bash -c "yes | pip install -r /fab_resh/requirements.txt &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000 
