# Generated by Django 2.2.10 on 2020-05-29 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_auto_20200528_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст ответа')),
                ('type', models.IntegerField(choices=[(0, 'Неправильный ответ'), (1, 'Правильный ответ')], default=0, verbose_name='Тип ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Question', verbose_name='Id вопроса')),
            ],
        ),
    ]
