# Generated by Django 2.2.10 on 2020-05-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='type',
            field=models.IntegerField(choices=[(1, 'Неправильный ответ'), (2, 'Правильный ответ')], default=0, verbose_name='Тип ответа'),
        ),
    ]
