# Generated by Django 2.2.10 on 2020-05-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='result',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='slug',
            field=models.SlugField(max_length=20),
        ),
        migrations.AlterField(
            model_name='result',
            name='user_id',
            field=models.IntegerField(blank=True),
        ),
    ]
