# Generated by Django 2.2.10 on 2020-05-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_auto_20200531_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='user_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
