# Generated by Django 2.2.10 on 2020-05-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0010_auto_20200531_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='slug',
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
